endroid_data_sanitize:
    entities:
        project:
            class: Endroid\DataSanitizeDemoBundle\Entity\Project
            fields: ['id', 'name']
        tag:
            class: Endroid\DataSanitizeDemoBundle\Entity\Tag
            fields: ['id', 'name']
        task:
            class: Endroid\DataSanitizeDemoBundle\Entity\Task
            fields: ['id', 'name', 'user.name', 'project.name']
        user:
            class: Endroid\DataSanitizeDemoBundle\Entity\User
            fields: ['id', 'name']
