endroid_data_sanitize:
    entities:
        project:
            class: Endroid\DataSanitizeDemoBundle\Entity\Project
            fields: ['id', 'referenceId', 'name']
            reference: referenceId
        tag:
            class: Endroid\DataSanitizeDemoBundle\Entity\Tag
            fields: ['id', 'name']
            reference: id
        task:
            class: Endroid\DataSanitizeDemoBundle\Entity\Task
            fields: ['id', 'name', 'user.name', 'project.name']
            reference: id
        user:
            class: Endroid\DataSanitizeDemoBundle\Entity\User
            fields: ['id', 'name']
            reference: id
